config/routes.rb
Rails.application.routes.draw do
  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'locations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @location = Location.new
    @locations = Location.all
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.infowindow location.address
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @hash = Gmaps4rails.build_markers(@location) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.infowindow location.address
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Locations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <div class="container" id="application-container"><%= yield %></div>
  
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Location", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/locations/_map_holder.html.erb
  <div style='width: 100%;'>
    <div id="map" style='width: 100%; height: 400px;'></div>
  </div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-6 col-sm-12">
  <h1>Locations</h1>

  <div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Address</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td class="col-md-5"><%= location.address %></td>
          <td class="col-md-7">
            <%= link_to 'Show', location %>
            <%= link_to 'Edit', edit_location_path(location) %>
            <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
        <tr>
        <%= form_for(@location) do |f| %>
          <td><%= f.text_field :address %></td>
          <td><%= f.submit "Submit New Location", :class => "btn btn-success" %></td>
        </tr>
    </tbody>
  </table>
  </div>

  <% end %>
</div>

<div class="col-sm-12 col-md-6">
  <%= render 'locations/map_holder' %>
</div>
<br>




<script src="//maps.google.com/maps/api/js?key=AIzaSyByqOXUPEjWbtJzJnWNpl6NCdkGA7DZ-Vg"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-4 col-md-offset-1 col-sm-12">
  
  <p>
    <strong>Address:</strong>
    <%= @location.address %>
  </p>
  
  <p>
    <strong>Latitude:</strong>
    <%= @location.latitude %>
  </p>
  
  <p>
    <strong>Longitude:</strong>
    <%= @location.longitude %>
  </p>
  
  
  <h2>Nearby Locations</h2>
  <ul>
    <% for location in @location.nearbys(10) %>
      <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
    <% end %>
  </ul>
  
  
  <%= link_to 'Edit', edit_location_path(@location) %> |
  <%= link_to 'Back', locations_path %>
</div>

<div class="col-md-7 col-sm-12">
  <%= render 'locations/map_holder' %>
</div>

<script src="//maps.google.com/maps/api/js?key=AIzaSyByqOXUPEjWbtJzJnWNpl6NCdkGA7DZ-Vg"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(18);
});
</script>